sudo: required 
dist: trusty 
services:
  - docker
language: generic 
compiler:
  - gcc
notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
      - gm130s@gmail.com
env:
  matrix:
    - ROS_DISTRO="jade"   ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu  USE_DEB=true
#    - ROS_DISTRO="jade"   ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu  USE_DEB=true
    - ROS_DISTRO="jade"   PRERELEASE=true
#    - ROS_DISTRO="indigo" ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu  USE_DEB=true
#    - ROS_DISTRO="indigo" ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu  USE_DEB=true
matrix:
  allow_failures:
    - env: ROS_DISTRO="indigo" ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu  USE_DEB=true
    - env: ROS_DISTRO="indigo" ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu  USE_DEB=true
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
  # Docker https://docs.docker.com/engine/installation/linux/ubuntulinux/
#  - if [[ ${PRERELEASE} == true ]]; then apt-get install apt-transport-https ca-certificates; apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D; fi
#  - if [[ ${PRERELEASE} == true ]]; then sudo -E sh -c 'echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main trusty main" > /etc/apt/sources.list.d/docker.list'; fi
#  - if [[ ${PRERELEASE} == true ]]; then apt-get update && apt-get purge lxc-docker; apt-cache policy docker-engine; fi
#  - if [[ ${PRERELEASE} == true ]]; then apt-get install linux-image-extra-$(uname -r); fi
#  - if [[ ${PRERELEASE} == true ]]; then apt-get install linux-image-generic-lts-trusty; fi
  - if [[ ${PRERELEASE} == true ]]; then sudo usermod -aG docker ubuntu; fi
  # ROS Buildfarm for prerelease http://wiki.ros.org/regression_tests#How_do_I_setup_my_system_to_run_a_prerelease.3F
  - if [[ ${PRERELEASE} == true ]]; then sudo -E sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'; fi
  - if [[ ${PRERELEASE} == true ]]; then sudo -E apt-key adv --keyserver hkp://pool.sks-keyservers.net --recv-key 0xB01FA116; fi
  # Buildfarm workaround for Python3 http://wiki.ros.org/regression_tests#How_do_I_setup_my_system_to_run_a_prerelease.3F
  - if [[ ${PRERELEASE} == true ]]; then sudo -E apt-get update && sudo -E apt-get install python3 python3-pip python-ros-buildfarm; fi
  - if [[ ${PRERELEASE} == true ]]; then sudo python3 -m pip install -U EmPy; fi
script:
  - if [[ ${PRERELEASE} == true ]]; then mkdir -p /tmp/prerelease_job; cd /tmp/prerelease_job; generate_prerelease_script.py https://raw.githubusercontent.com/ros-infrastructure/ros_buildfarm_config/production/index.yaml jade default ubuntu trusty amd64 moveit_msgs --level 1 --output-dir ./; fi
  - if [[ ${PRERELEASE} == true ]]; then ./prerelease.sh; fi
  - if [[ ${PRERELEASE} != true ]]; then source .ci_config/travis.sh; fi
#  - source ./travis.sh  # Enable this when you have a package-local script 
